### ISSUE TITLE
[QUESTION] Is the webhook working

### ISSUE THREAD

**Issue by MakeShiftArtist** [ifunny-co/iFunny.ts#1]
### Prerequisites
* [ ] Have you read the documentation?
* [ ] Are you running the latest version?
* [ ] Did you check [issues](https://github.com/MakeShiftArtist/tsproject-template/issues) to see if your question has already been answered?
* [ ] Is your question about this projects API?

### Description

**Expected/Desired behavior:**

**Actual behavior:**

**Comment by MakeShiftArtist** [comment]
Yes it is

**Comment by gecko10000** [comment]
no it's not

**Comment by MakeShiftArtist** [comment]
yes it is >:(
